/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class application_Scheduling */

#ifndef _Included_application_Scheduling
#define _Included_application_Scheduling
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     application_Scheduling
 * Method:    runSchedule
 * Signature: (Ljava/lang/String;Ljava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_application_Scheduling_runSchedule
  (JNIEnv *, jobject, jstring, jstring, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
